name: Build

on:
  workflow_dispatch:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Verify
        run: mvn -B clean verify
        env:
          AWS_ACCESS_KET_ID: ${{ secrets.AWS_ACCESS_KET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          PAYMENT_API_KEY: ${{ secrets.PAYMENT_API_KEY }}
          PAYMENT_SIGHING_SECRET: ${{ secrets.PAYMENT_SIGHING_SECRET }}
      - name: Test Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
