name: catalog-image

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'develop'

env:
  IMAGE_NAME: catalog-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'zulu'
    - name: Change direcotry to catalog-service
      run: cd catalog-service
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Grant execute permission for gradlew
      run: chmod +x mvnw
    - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
      run: ./mvnw spring-boot:build-image -Dmodule.image.name=$IMAGE_NAME 
    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        docker push feduuusha/$IMAGE_NAME:latest
